name: 'Dynamic Ruby versions action'

description: 'GitHub Action to build Ruby versions dynamically'

inputs:
  type:
    description: 'See https://cache.ruby-lang.org/pub/misc/ci_versions/'
    required: true
    default: 'cruby'

outputs:
  versions:
    description: 'Ruby versions built'
    value: ${{ steps.build-versions.outputs.versions }}

runs:
  using: composite
  steps:
    - id: build-versions
      shell: bash
      run: |
        versions="$(curl -s 'https://cache.ruby-lang.org/pub/misc/ci_versions/${{ inputs.type }}.json' | jq -c)"
        echo "Fetched Ruby versions: ${versions}"
        echo "::set-output name=versions::${versions}"
