name: 'Dynamic Ruby versions action'

description: 'GitHub Action to build Ruby versions dynamically'

inputs:
  type:
    # See https://cache.ruby-lang.org/pub/misc/ci_versions/
    description: '"cruby", "cruby-jruby", "cruby-truffleruby", or "all"'
    required: true
    default: 'cruby'
  add:
    description: 'Additional versions (must be JSON string)'
    required: false
    default: ''

outputs:
  versions:
    description: 'Ruby versions built'
    value: ${{ steps.build-versions.outputs.versions }}

runs:
  using: composite
  steps:
    - id: build-versions
      shell: bash
      run: |
        versions="$(curl -s "https://cache.ruby-lang.org/pub/misc/ci_versions/${TYPE}.json" | jq -c ". + [${ADD}]")"
        echo "Fetched Ruby versions: ${versions}"
        echo "::set-output name=versions::${versions}"
      env:
        TYPE: ${{ inputs.type }}
        ADD: ${{ inputs.add }}
